### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by pixtolero** [YohanWD/WTManageSquadron#22]
I've got this issue now 

`Traceback (most recent call last):
  File "main.py", line 136, in <module>
    main()
  File "main.py", line 79, in main
    scraping.scrap_squadron_profile_page(html_file_path),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils/scraping.py", line 25, in scrap_squadron_profile_page
    tmp_el = squad_member_html.find_all("div")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
`

**Comment by pixtolero** [comment]
working again
